OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET UTF8
INFILE 'AccessLevels.csv'
TRUNCATE
INTO TABLE INFERNAL.ACCESSLEVELS2
FIELDS TERMINATED BY ";"
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
( access_level_id, access_level, description char(300) )