OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET UTF8
INFILE 'AssignedCases.csv'
TRUNCATE
INTO TABLE INFERNAL.ASSIGNEDCASES2
FIELDS TERMINATED BY ";"
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
( employee_id, case_id)