OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET UTF8
INFILE 'Departments.csv'
TRUNCATE
INTO TABLE INFERNAL.DEPARTMENTS2
FIELDS TERMINATED BY ";"
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
( department_id, department_name char(200) , description char(200) )