OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET UTF8
INFILE 'Posts.csv'
TRUNCATE
INTO TABLE INFERNAL.POSTS2
FIELDS TERMINATED BY ";"
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
( post_id, post_name char(200) , description char(200) )