OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET UTF8
INFILE 'StatusStates.csv'
TRUNCATE
INTO TABLE INFERNAL.STATUSSTATES2
FIELDS TERMINATED BY ";"
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
( status_id, description char(200) )